module.exports = {
  guideSidebar: [  
    {
      type: 'autogenerated',
      dirName: 'guides', // '.' means the current docs folder
    }
  ],
  brandingSidebar: [{type: 'autogenerated', dirName: 'branding'}],
  componentSidebar: [{type: 'autogenerated', dirName: 'components'}],
};
