module.exports = {
  guideSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
  ],
  brandingSidebar: [{type: 'autogenerated', dirName: 'branding'}],
  componentSidebar: [{type: 'autogenerated', dirName: 'components'}],
};
